2015-09-05 21:39:19,703 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-05 21:49:32,381 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-05 21:49:37,204 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-05 21:57:30,122 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-05 22:31:49,237 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-05 22:31:49,652 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-06 12:39:57,098 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-06 20:08:57,830 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-06 22:01:50,787 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-06 22:02:27,481 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-06 22:02:46,563 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-06 22:03:03,921 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-06 22:03:04,170 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-06 22:03:34,715 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-07 09:02:57,209 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-07 09:04:53,429 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-07 09:06:28,386 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-07 09:09:33,038 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-07 09:11:30,229 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-07 09:12:18,909 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-07 09:12:33,061 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-07 09:12:33,314 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-07 09:13:07,952 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-07 09:18:02,810 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-07 09:21:39,656 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-07 09:22:11,484 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-07 09:26:26,929 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-07 09:28:16,011 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-07 09:28:59,086 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-07 09:28:59,341 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-07 14:36:50,771 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-07 14:36:51,250 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-07 20:45:07,095 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-07 20:45:07,500 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-09 14:12:36,526 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-09 14:12:36,898 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 15:31:36,709 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 15:31:37,073 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 15:39:15,705 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 15:39:15,932 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 15:40:10,696 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 15:46:51,530 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 15:47:00,392 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 15:49:21,680 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 15:50:27,845 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 15:50:30,399 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 15:50:40,098 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 15:50:40,318 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 15:53:55,989 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 15:53:56,215 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 16:00:27,212 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 16:01:16,043 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 16:02:12,015 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 16:02:12,241 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 16:05:48,362 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 16:06:13,853 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 16:07:17,687 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 16:09:50,720 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-13 16:12:17,893 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 16:17:16,032 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 16:21:12,886 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 16:21:47,762 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 16:22:35,959 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 16:23:51,413 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 17:10:34,791 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-13 20:33:55,259 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 20:35:22,398 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 20:36:23,220 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 20:36:55,089 INFO: sciral-dev startup [in /Users/alexh/Documents/code/sciral/app/__init__.py:17]
2015-09-13 20:55:15,412 INFO: sciral-dev startup [in /home/a/ah/aherns/sciral/app/__init__.py:17]
2015-09-13 20:55:16,763 INFO: sciral-dev startup [in /home/a/ah/aherns/sciral/app/__init__.py:17]
2015-09-13 21:04:39,077 INFO: sciral-dev startup [in /home/a/ah/aherns/sciral/app/__init__.py:17]
2015-09-13 21:04:40,341 INFO: sciral-dev startup [in /home/a/ah/aherns/sciral/app/__init__.py:17]
2015-09-13 21:12:50,083 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:12:51,927 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:19:12,846 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:22:52,868 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:23:19,481 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:24:11,045 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:26:26,536 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:28:29,060 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:28:30,719 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:29:05,591 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:32:10,527 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:34:21,026 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:35:00,133 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:35:14,061 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:35:21,256 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:36:24,198 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:36:56,575 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:40:15,334 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:40:20,966 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:44:54,084 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:46:26,076 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:46:42,251 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:46:47,648 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:47:01,830 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:48:17,861 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:49:20,713 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:51:13,852 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:51:23,304 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:51:26,032 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:51:28,971 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:51:32,036 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:51:35,097 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:51:41,026 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:51:44,005 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:51:47,078 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:51:50,072 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:55:13,694 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:55:53,227 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 21:55:59,188 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 22:20:07,441 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 22:20:10,708 ERROR: Exception on /search [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 51, in search
    db.session.commit()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 776, in commit
    self.transaction.commit()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 377, in commit
    self._prepare_impl()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 357, in _prepare_impl
    self.session.flush()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 570, in _emit_insert_statements
    execute(statement, multiparams)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 928, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 433, in do_executemany
    cursor.executemany(statement, parameters)
IntegrityError: (IntegrityError) PRIMARY KEY must be unique u'INSERT INTO article (id, title, doi, journal, score, abstract, default_set, pub_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' ((4461873, 'Discovery of phosphonic acid natural products by mining the genomes of 10,000 actinomycetes', u'10.1073/pnas.1500873112', u'Proceedings of the National Academy of Sciences of the United States of America', 62, 'Although natural products have been a particularly rich source of human medicines, activity-based screening results in a very high rate of rediscovery of known molecules. Based on the large number of natural product biosynthetic genes in microbial genomes, many have proposed "genome mining" as an alternative approach for discovery efforts; however, this idea has yet to be performed experimentally on a large scale. Here, we demonstrate the feasibility of large-scale, high-throughput genome mining by screening a collection of over 10,000 actinomycetes for the genetic potential to make phosphonic acids, a class of natural products with diverse and useful bioactivities. Genome sequencing identified a diverse collection of phosphonate biosynthetic gene clusters within 278 strains. These clusters were classified into 64 distinct groups, of which 55 are likely to direct the synthesis of unknown compounds. Characterization of strains within five of these groups resulted in the discovery of a new archetypical pathway for phosphonate biosynthesis, the first (to our knowledge) dedicated pathway for H-phosphinates, and 11 previously undescribed phosphonic acid natural products. Among these compounds are argolaphos, a broad-spectrum antibacterial phosphonopeptide composed of aminomethylphosphonate in peptide linkage to a rare amino acid N(5)-hydroxyarginine; valinophos, an N-acetyl l-Val ester of 2,3-dihydroxypropylphosphonate; and phosphonocystoximate, an unusual thiohydroximate-containing molecule representing a new chemotype of sulfur-containing phosphonate natural products. Analysis of the genome sequences from the remaining strains suggests that the majority of the phosphonate biosynthetic repertoire of Actinobacteria has been captured at the gene level. This dereplicated strain collection now provides a reservoir of numerous, as yet undiscovered, phosphonate natural products.', 0, None), (4488623, 'Small-scale gene duplications played a major role in the recent evolution of wheat chromosome 3B', u'10.1186/s13059-015-0754-6', u'Genome Biology (Online Edition)', 28, 'Bread wheat is not only an important crop, but its large (17 Gb), highly repetitive, and hexaploid genome makes it a good model to study the organization and evolution of complex genomes. Recently, we produced a high quality reference sequence of wheat chromosome 3B (774Mb), which provides an excellent opportunity to study the evolutionary dynamics of a large and polyploid genome, specifically the impact of single gene duplications.\nWe find that 27% of the 3B predicted genes are non-syntenic with the orthologous chromosomes of Brachypodium distachyon, Oryza sativa, and Sorghum bicolor, whereas, by applying the same criteria, non-syntenic genes represent on average only 10% of the predicted genes in these three model grasses. These non-syntenic genes on 3B have high sequence similarity to at least one other gene in the wheat genome, indicating that hexaploid wheat has undergone massive small-scale interchromosomal gene duplications compared to other grasses. Insertions of non-syntenic genes occurred at a similar rate along the chromosome, but these genes tend to be retained at a higher frequency in the distal, recombinogenic regions. The ratio of non-synonymous to synonymous substitution rates showed a more relaxed selection pressure for non-syntenic genes compared to syntenic genes, and gene ontology analysis indicated that non-syntenic genes may be enriched in functions involved in disease resistance.\nOur results highlight the major impact of single gene duplications on the wheat gene complement and confirm the accelerated evolution of the Triticeae lineage among grasses.', 0, None), (4482153, 'Calls for Caution in Genome Engineering Should Be a Model for Similar Dialogue on Pandemic Pathogen Research', u'10.7326/m15-1048', u'Annals of Internal Medicine', 24, '', 0, None), (4436596, 'Biohackers gear up for genome editing', u'10.1038/524398a', u'Nature', 797, '', 0, None), (2046076, 'Is the $1,000 genome for real?', u'10.1038/nature.2014.14530', u'Nature', 298, '', 0, None), (4490459, 'A Gene Gravity Model for the Evolution of Cancer Genomes: A Study of 3,000 Cancer Genomes across 9 Cancer Types.', u'10.1371/journal.pcbi.1004497', u'PLoS Computational Biology', 20, 'Cancer development and progression result from somatic evolution by an accumulation of genomic alterations. The effects of those alterations on the fitness of somatic cells lead to evolutionary adaptations such as increased cell proliferation, angiogenesis, and altered anticancer drug responses. However, there are few general mathematical models to quantitatively examine how perturbations of a single gene shape subsequent evolution of the cancer genome. In this study, we proposed the gene gravity model to study the evolution of cancer genomes by incorporating the genome-wide transcription and somatic mutation profiles of ~3,000 tumors across 9 cancer types from The Cancer Genome Atlas into a broad gene network. We found that somatic mutations of a cancer driver gene may drive cancer genome evolution by inducing mutations in other genes. This functional consequence is often generated by the combined effect of genetic and epigenetic (e.g., chromatin regulation) alterations. By quantifying cancer genome evolution using the gene gravity model, we identified six putative cancer genes (AHNAK, COL11A1, DDX3X, FAT4, STAG2, and SYNE1). The tumor genomes harboring the nonsynonymous somatic mutations in these genes had a higher mutation density at the genome level compared to the wild-type groups. Furthermore, we provided statistical evidence that hypermutation of cancer driver genes on inactive X chromosomes is a general feature in female cancer genomes. In summary, this study sheds light on the functional consequences and evolutionary characteristics of somatic mutations during tumorigenesis by propelling adaptive cancer genome evolution, which would provide new perspectives for cancer research and therapeutics.', 0, None), (4458817, 'Evaluating the role of admixture in cancer therapy via in vitro drug response and multivariate genome-wide associations.', u'10.2217/pgs.15.85', u'Pharmacogenomics', 20, 'We investigate the role of ethnicity and admixture in drug response across a broad group of chemotherapeutic drugs. Also, we generate hypotheses on the genetic variants driving differential drug response through multivariate genome-wide association studies.\nImmortalized lymphoblastoid cell lines from 589 individuals (Hispanic or non-Hispanic/Caucasian) were used to investigate dose-response for 28 chemotherapeutic compounds. Univariate and multivariate statistical models were used to elucidate associations between genetic variants and differential drug response as well as the role of ethnicity in drug potency and efficacy.\nFor many drugs, the variability in drug response appears to correlate with self-reported race and estimates of genetic ancestry. Additionally, multivariate genome-wide association analyses offered interesting hypotheses governing these differential responses.', 0, None), (4474905, 'Uniform and accurate single-cell sequencing based on emulsion whole-genome amplification', u'10.1073/pnas.1513988112', u'Proceedings of the National Academy of Sciences of the United States of America', 22, 'Whole-genome amplification (WGA) for next-generation sequencing has seen wide applications in biology and medicine when characterization of the genome of a single cell is required. High uniformity and fidelity of WGA is needed to accurately determine genomic variations, such as copy number variations (CNVs) and single-nucleotide variations (SNVs). Prevailing WGA methods have been limited by fluctuation of the amplification yield along the genome, as well as false-positive and -negative errors for SNV identification. Here, we report emulsion WGA (eWGA) to overcome these problems. We divide single-cell genomic DNA into a large number (10(5)) of picoliter aqueous droplets in oil. Containing only a few DNA fragments, each droplet is led to reach saturation of DNA amplification before demulsification such that the differences in amplification gain among the fragments are minimized. We demonstrate the proof-of-principle of eWGA with multiple displacement amplification (MDA), a popular WGA method. This easy-to-operate approach enables simultaneous detection of CNVs and SNVs in an individual human cell, exhibiting significantly improved amplification evenness and accuracy.', 0, None)  ... displaying 10 of 25 total bound parameter sets ...  (4468678, 'Development and preliminary evaluation of an online educational video about whole-genome sequencing for research participants, patients, and the general public.', u'10.1038/gim.2015.118', u'Genetics in Medicine', 17, 'As whole-genome sequencing (WGS) increases in availability, WGS educational aids are needed for research participants, patients, and the general public. Our aim was therefore to develop an accessible and scalable WGS educational aid.\nWe engaged multiple stakeholders in an iterative process over a 1-year period culminating in the production of a novel 10-minute WGS educational animated video, "Whole Genome Sequencing and You" (https://goo.gl/HV8ezJ). We then presented the animated video to 281 online-survey respondents (the video-information group). There were also two comparison groups: a written-information group (n = 281) and a no-information group (n = 300).\nIn the video-information group, 79% reported the video was easy to understand, satisfaction scores were high (mean 4.00 on 1-5 scale, where 5 = high satisfaction), and knowledge increased significantly. There were significant differences in knowledge compared with the no-information group but few differences compared with the written-information group. Intention to receive personal results from WGS and decisional conflict in response to a hypothetical scenario did not differ between the three groups.\nThe educational animated video, "Whole Genome Sequencing and You," was well received by this sample of online-survey respondents. Further work is needed to evaluate its utility as an aid to informed decision making about WGS in other populations.Genet Med advance online publication 03 September 2015Genetics in Medicine (2015); doi:10.1038/gim.2015.118.', 0, None), (4473294, 'Inferring Bottlenecks from Genome-Wide Samples of Short Sequence Blocks', u'10.1534/genetics.115.179861', u'Genetics', 10, "The advent of the genomic era has necessitated the development of methods capable of analyzing large volumes of genomic data efficiently. Being able to reliably identify bottlenecks - extreme population size changes of short duration - is not only interesting in the context of speciation and extinction but also matters (as a null model) when inferring selection. Bottlenecks can be detected in polymorphism data via their distorting effect on the shape of the underlying genealogy. Here, we use the generating function of genealogies to derive the probability of mutational configurations in short sequence blocks under a simple bottleneck model. Given a large number of non-recombining blocks, we can compute maximum likelihood estimates of the time and strength of the bottleneck. Our method relies on a simple summary of the joint distribution of polymorphic sites. We extend the site frequency spectrum by counting mutations in frequency classes in short sequence blocks. Using linkage information over short distances in this way gives greater power to detect bottlenecks than the site frequency spectrum and potentially opens up a wide range of demographic histories to blockwise inference. Finally, we apply our method to genomic data from a species of pig (Sus cebifrons) endemic to islands in the center and west of the Philippines to estimate whether a bottleneck occurred upon island colonization and compare our scheme to Li and Durbin's pairwise sequentially Markovian coalescent (PSMC) both for the pig data and using simulations.", 0, None))
2015-09-13 22:20:50,411 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-13 22:20:51,817 ERROR: Exception on /search [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 51, in search
    db.session.commit()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 776, in commit
    self.transaction.commit()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 377, in commit
    self._prepare_impl()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 357, in _prepare_impl
    self.session.flush()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 570, in _emit_insert_statements
    execute(statement, multiparams)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 928, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 433, in do_executemany
    cursor.executemany(statement, parameters)
IntegrityError: (IntegrityError) PRIMARY KEY must be unique u'INSERT INTO article (id, title, doi, journal, score, abstract, default_set, pub_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' ((1941770, 'Cannabis Extract Treatment for Terminal Acute Lymphoblastic Leukemia with a Philadelphia Chromosome Mutation', u'10.1159/000356446', u'Case Reports in Oncology', 335, 'Acute lymphoblastic leukemia (ALL) is a cancer of the white blood cells and is typically well treated with combination chemotherapy, with a remission state after 5 years of 94% in children and 30-40% in adults. To establish how aggressive the disease is, further chromosome testing is required to determine whether the cancer is myeloblastic and involves neutrophils, eosinophils or basophils, or lymphoblastic involving B or T lymphocytes. This case study is on a 14-year-old patient diagnosed with a very aggressive form of ALL (positive for the Philadelphia chromosome mutation). A standard bone marrow transplant, aggressive chemotherapy and radiation therapy were revoked, with treatment being deemed a failure after 34 months. Without any other solutions provided by conventional approaches aside from palliation, the family administered cannabinoid extracts orally to the patient. Cannabinoid resin extract is used as an effective treatment for ALL with a positive Philadelphia chromosome mutation and indications of dose-dependent disease control. The clinical observation in this study revealed a rapid dose-dependent correlation.', 0, None), (4407761, 'Anti-inflammatory mechanisms of IFN- studied in experimental autoimmune encephalomyelitis reveal neutrophils as a potential target in multiple sclerosis.', u'10.3389/fnins.2015.00287', u'Frontiers in Neuroscience', 11, 'Multiple sclerosis (MS) is an autoimmune disease of the central nervous system (CNS) mediated by T helper (h)1 and/or Th17 CD4 T cells that drive inflammatory lesion development along with demyelination and neuronal damage. Defects in immune regulatory mechanisms are thought to play a role in the pathogenesis of MS. While an early clinical trial indicated that IFN- administration was detrimental to MS, studies in the mouse model of MS, experimental autoimmune encephalomyelitis (EAE), indicated that IFN- exhibits a number of anti-inflammatory properties within the CNS. These mechanisms include inhibition of IL-17 production, induction of regulatory T cells, T cell apoptosis and regulation of chemokine production. Mice deficient in IFN- or its receptor were instrumental in deciphering the anti-inflammatory properties of IFN- in the CNS. In particular, they revealed that IFN- is a major regulator of neutrophil recruitment into the CNS, which by a variety of mechanisms including disruption of the blood-brain-barrier (BBB) and production of reactive oxygen species are thought to contribute to the onset and progression of EAE. Neutrophils were also shown to be instrumental in EAE relapses. To date neutrophils have not been appreciated as a driver of MS, but more recently based largely on strong EAE data this view is being reevaluated by some investigators in the field.', 0, None), (2121143, 'Neurobehavioural effects of developmental toxicity', u'10.1016/s1474-4422(13)70278-3', u'Lancet Neurology', 1797, 'Neurodevelopmental disabilities, including autism, attention-deficit hyperactivity disorder, dyslexia, and other cognitive impairments, affect millions of children worldwide, and some diagnoses seem to be increasing in frequency. Industrial chemicals that injure the developing brain are among the known causes for this rise in prevalence. In 2006, we did a systematic review and identified five industrial chemicals as developmental neurotoxicants: lead, methylmercury, polychlorinated biphenyls, arsenic, and toluene. Since 2006, epidemiological studies have documented six additional developmental neurotoxicants-manganese, fluoride, chlorpyrifos, dichlorodiphenyltrichloroethane, tetrachloroethylene, and the polybrominated diphenyl ethers. We postulate that even more neurotoxicants remain undiscovered. To control the pandemic of developmental neurotoxicity, we propose a global prevention strategy. Untested chemicals should not be presumed to be safe to brain development, and chemicals in existing use and all new chemicals must therefore be tested for developmental neurotoxicity. To coordinate these efforts and to accelerate translation of science into prevention, we propose the urgent formation of a new international clearinghouse.', 0, None), (1763120, 'The virus-receptor interaction in the replication of feline immunodeficiency virus (FIV).', u'10.1016/j.coviro.2013.08.003', u'Current Opinion in Virology', 11, 'The feline and human immunodeficiency viruses (FIV and HIV) target helper T cells selectively, and in doing so they induce a profound immune dysfunction. The primary determinant of HIV cell tropism is the expression pattern of the primary viral receptor CD4 and co-receptor(s), such as CXCR4 and CCR5. FIV employs a distinct strategy to target helper T cells; a high affinity interaction with CD134 (OX40) is followed by binding of the virus to its sole co-receptor, CXCR4. Recent studies have demonstrated that the way in which FIV interacts with its primary receptor, CD134, alters as infection progresses, changing the cell tropism of the virus. This review examines the contribution of the virus-receptor interaction to replication in vivo as well as the significance of these findings to the development of vaccines and therapeutics.', 0, None), (4458874, 'Immune Parameters That Distinguish Multiple Sclerosis Patients from Patients with Other Neurological Disorders at Presentation.', u'10.1371/journal.pone.0135434', u'PLoS ONE', 10, 'Multiple sclerosis (MS) is an inflammatory, demyelinating disease of the central nervous system. Effector T helper cells, mainly Th1 and Th17, cytotoxic T-cells, B-cells, macrophages, microglia, and the cytokines they secrete, are implicated in the initiation and maintenance of a deregulated immune response to myelin antigens and the ensuing immune-mediated demyelination. In this study, we investigated whether signature cytokines exist in MS patients at presentation to gain an insight into the underlying immunopathogenic processes at the early stage of the disease.\nWe collected serum and cerebrospinal fluid (CSF) samples from 123 patients at presentation, eventually diagnosed with MS or non-inflammatory (NIND) or inflammatory neurological diseases (IND) or symptomatic controls (SC). The levels of cytokines IFN-, TNF-, TGF-1, IL-2, IL-4, IL-6, IL-10 and IL-17 were measured, and cytokine ratios, such as Th1/Th2, Th1/Th17, and Type-1/Type-2, were calculated. All parameters were tested for their correlations with the intrathecal IgG synthesis.\nCytokine levels in CSF were lower than in serum in all the patients, with the exception of IL-6. Serum or CSF cytokine levels of MS patients did not differ significantly from NIND or SC, with the exception of serum IFN- and TNF- that were significantly higher in NIND. IND patients presented with the highest levels of all cytokines in serum and CSF, with the exception of serum IL-10 and CSF IL-17. MS patients had a significantly lower serum Th1/Th2 ratio compared to the NIND and IND groups, and significantly lower serum Type-1/Type-2, IFN-/IL-10 and CSF Th1/Th17 ratios compared to IND patients. MS patients had a significantly higher CSF IL-17/IL-10 ratio compared to IND patients. The IgG index was higher in MS patients compared to the control groups; the differences reached statistical significance between the MS and the NIND and SC groups. Reiber-Felgenhauer analysis of the QIgG and QAlb indices revealed higher intrathecal IgG synthesis in MS patients, and higher blood-CSF barrier dysfunction in IND patients. The IgG index correlated with CSF IL-4 in MS patients only.\nWe found no signature cytokines or profiles thereof in MS patients at presentation. Only IND patients presented with a clear Th1 cytokine polarization in serum and CSF. The parameters that distinguished MS patients from patients with other neurological disorders were IgG intrathecal synthesis, the IgG index and its correlation with CSF IL-4 levels.', 0, None), (4428397, 'Cysteinyl leukotrienes mediate lymphokine killer activity induced by NKG2D and IL-15 in cytotoxic T cells during celiac disease.', u'10.1084/jem.20150303', u'The Journal of Experimental Medicine', 10, 'Eicosanoids are inflammatory mediators that play a key but incompletely understood role in linking the innate and adaptive immune systems. Here, we show that cytotoxic effector T cells (CTLs) are capable of both producing and responding to cysteinyl leukotrienes (CystLTs), allowing for the killing of target cells in a T cell receptor-independent manner. This process is dependent on the natural killer receptor NKG2D and exposure to IL-15, a cytokine induced in distressed tissues. IL-15 and NKG2D signaling drives the up-regulation of key enzymes implicated in the synthesis of CystLTs, as well as the expression of CystLT receptors, suggesting a positive feedback loop. Finally, although the CystLT pathway has been previously linked to various allergic disorders, we provide unexpected evidence for its involvement in the pathogenesis of celiac disease (CD), a T helper 1 cell-mediated enteropathy induced by gluten. These findings provide new insights into the cytolytic signaling pathway of NKG2D and the pathogenesis of organ-specific immune disorders. Furthermore, they suggest that the blockade of CystLT receptors may represent a potent therapeutic target for CD or potentially other autoimmune disorders in which NKG2D has been implicated.', 0, None), (4333227, 'The transcription factor TCF-1 initiates the differentiation of TFH cells during acute viral infection', u'10.1038/ni.3229', u'Nature Immunology', 16, "Induction of the transcriptional repressor Bcl-6 in CD4(+) T cells is critical for the differentiation of follicular helper T cells (TFH cells), which are essential for B cell-mediated immunity. In contrast, the transcription factor Blimp1 (encoded by Prdm1) inhibits TFH differentiation by antagonizing Bcl-6. Here we found that the transcription factor TCF-1 was essential for both the initiation of TFH differentiation and the effector function of differentiated TFH cells during acute viral infection. Mechanistically, TCF-1 bound directly to the Bcl6 promoter and Prdm1 5' regulatory regions, which promoted Bcl-6 expression but repressed Blimp1 expression. TCF-1-null TFH cells upregulated genes associated with non-TFH cell lineages. Thus, TCF-1 functions as an important hub upstream of the Bcl-6-Blimp1 axis to initiate and secure the differentiation of TFH cells during acute viral infection.", 0, None), (4482326, 'Identification of transcription coactivator OCA-B-dependent genes involved in antigen-dependent B cell differentiation by cDNA array analyses', u'10.1073/pnas.1033108100', u'Proceedings of the National Academy of Sciences of the United States of America', 6, 'The tissue-specific transcriptional coactivator OCA-B is required for antigen-dependent B cell differentiation events, including germinal center formation. However, the identity of OCA-B target genes involved in this process is unknown. This study has used large-scale cDNA arrays to monitor changes in gene expression patterns that accompany mature B cell differentiation. B cell receptor ligation alone induces many genes involved in B cell expansion, whereas B cell receptor and helper T cell costimulation induce genes associated with B cell effector function. OCA-B expression is induced by both B cell receptor ligation alone and helper T cell costimulation, suggesting that OCA-B is involved in B cell expansion as well as B cell function. Accordingly, several genes involved in cell proliferation and signaling, such as Lck, Kcnn4, Cdc37, cyclin D3, B4galt1, and Ms4a11, have been identified as OCA-B-dependent genes. Further studies on the roles played by these genes in B cells will contribute to an understanding of B cell differentiation.', 0, None)  ... displaying 10 of 25 total bound parameter sets ...  (4150980, 'Rhodiola rosea suppresses thymus T-lymphocyte apoptosis by downregulating tumor necrosis factor--induced protein8-like-2 in septic rats.', u'10.3892/ijmm.2015.2241', u'International Journal of Molecular Medicine', 4, "In recent years, several studies have shown that Rhodiolarosea can enhance cellular immunity and humoral immune function in mice, and thus, it has become a research hotspot. However, its underlying mechanism of action has remained elusive. The present study investigated whether Rhodiolarosea was able to downregulate the expression of tumor necrosis factor--inducible protein 8-like2 (TIPE2), thereby inhibiting the expression of apoptotic genes, attenuating Tlymphocyte apoptosis and improving immunity in septic mice. A mouse model of caecal ligation and puncture (CLP)induced sepsis was established, and animals in the treatment group were pre-treated with an intraperitoneal injection of Rhodiolarosea extract, while animals in the control group and sham-operated group were injected with an equivalent amount of normal saline. TIPE2, B-cell lymphoma2 (Bcl2), Fas and Fas ligand (FasL) mRNA and protein levels in thymic T cells were determined using reverse transcription quantitative polymerase chain reaction and western blot analysis, respectively. Furthermore, the thymus Tlymphocyte apoptosis rate, thymus Tlymphocyte count and thymus Tlymphocyte subsets were assessed using flow cytometry. Levels of T-helper cell type1 (Th1) cytokines [Interleukin (IL)-2, IL-12 and interferon (IFN)-] and Th2 cytokines (IL-4 and IL-10) were determined using ELISA. The results showed that, compared to that in the CLP group, the expression of TIPE2, Fas and FasL in the treatment group was significantly decreased, while the expression of Bcl-2 was increased (P<0.05). The thymus lymphocyte count in the CLP group was significantly higher compared with that in the treatment group (P<0.05). Furthermore, the apoptotic rate of thymus T-lymphocytes in the treatment group was significantly lower than that in the CLP group (P<0.05). In addition, treatment with Rhodiolarosea rescued decreased in the counts of the CD3+T and CD4+T subsets of thymus Tlymphocytes in the CLP group (P<0.05), while not affecting the increased levels of Th2 cytokines (IL-4 and IL-10) in the CLP group compared with those in the control groups. In addition, the Th1 cytokines (IL-12, IL-2 and IFN-) were significantly increased (P<0.05) in the CLP group, and treatment with Rhodiolarosea led to further increases. The thymus index of septic mice treated with Rhodiolarosea as well as their survival rate were improved as compared with those in the CLP group. These findings suggested that Rhodiola rosea has protective effects against sepsis by decreasing apoptosis, increasing Th1 cytokines and enhancing the host's immunity via the regulation of TIPE2 expression.", 0, None), (4133281, 'Early Development in the Peritoneal Cavity of CD49dhigh Th1 Memory Phenotype CD4+ T Cells with Enhanced B Cell Helper Activity', u'10.4049/jimmunol.1401661', u'The Journal of Immunology', 3, 'The Th cells that regulate peritoneal B-1 cell functions have not yet been well characterized. To address this question, we investigated peritoneal CD4(+) T cells, observed a high frequency of the conjugates of B-CD4(+) T cells in the peritoneal cavity, and identified a population of CD49d(high)CD4(+) T cells that constituted about half of all CD4(+) T cells in the peritoneal cavity, but were rarely found in other compartments. Peritoneal CD49d(high)CD4(+) T cells were CD44(high)CD62L(low); expressed integrin 41 and CXCR3; and rapidly secreted IFN-, TNF-, and IL-2, showing features of proinflammatory Th1 cells. Peritoneal CD49d(high)CD4(+) T cells developed spontaneously, were detected at the age of 12 d, and showed stem cell-like properties. Their development was observed in mice deficient for signaling lymphocytic activation molecule-associated protein, but not in athymic nude mice and mice lacking in expression of MHC class II on thymic epithelial cells. Peritoneal CD49d(high)CD4(+) T cells were more resistant to irradiation and more sensitive to NAD-induced cell death than CD49d(low)CD4(+) T cells. Notably, peritoneal CD49d(high)CD4(+) T cells also showed some characteristics of follicular Th cells, such as the expression of programmed cell death 1, ICOS, IL-21, and CXCR5. Moreover, peritoneal CD49d(high)CD4(+) T cells enhanced the secretion of IgM Abs by B-1a cells and IgG Abs by splenic B cells. These data suggest that peritoneal CD49d(high)CD4(+) T cells may be innate-like CD4(+) T cells, which develop early and have a dual capacity to support both humoral and cellular immunity.', 0, None))
2015-09-13 22:21:08,820 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 08:20:46,833 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 08:20:46,834 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 08:20:47,965 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 08:21:03,883 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 08:21:14,379 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 08:21:38,706 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 19:44:14,422 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 19:44:18,260 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 19:44:24,194 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 19:44:30,295 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 19:44:36,275 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 19:59:37,935 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-14 20:03:27,156 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-14 20:04:24,777 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 20:04:28,420 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 20:04:54,623 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-14 20:05:47,344 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-14 20:08:01,124 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-14 20:11:08,419 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-14 20:11:27,206 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-14 20:16:18,744 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-14 20:17:21,285 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 20:17:46,997 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-14 20:24:56,656 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 27, in results
    articles= models.Article.query.filter(models.Article.default_set == False).order_by(models.Article.score.desc()).all()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2300, in all
    return list(self)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
    return self._execute_and_instances(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2427, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) no such table: article u'SELECT article.id AS article_id, article.title AS article_title, article.doi AS article_doi, article.journal AS article_journal, article.score AS article_score, article.abstract AS article_abstract, article.default_set AS article_default_set, article.pub_date AS article_pub_date \nFROM article \nWHERE article.default_set = 0 ORDER BY article.score DESC' ()
2015-09-14 20:24:59,979 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 27, in results
    articles= models.Article.query.filter(models.Article.default_set == False).order_by(models.Article.score.desc()).all()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2300, in all
    return list(self)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
    return self._execute_and_instances(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2427, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) no such table: article u'SELECT article.id AS article_id, article.title AS article_title, article.doi AS article_doi, article.journal AS article_journal, article.score AS article_score, article.abstract AS article_abstract, article.default_set AS article_default_set, article.pub_date AS article_pub_date \nFROM article \nWHERE article.default_set = 0 ORDER BY article.score DESC' ()
2015-09-14 20:25:02,733 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 27, in results
    articles= models.Article.query.filter(models.Article.default_set == False).order_by(models.Article.score.desc()).all()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2300, in all
    return list(self)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
    return self._execute_and_instances(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2427, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) no such table: article u'SELECT article.id AS article_id, article.title AS article_title, article.doi AS article_doi, article.journal AS article_journal, article.score AS article_score, article.abstract AS article_abstract, article.default_set AS article_default_set, article.pub_date AS article_pub_date \nFROM article \nWHERE article.default_set = 0 ORDER BY article.score DESC' ()
2015-09-14 20:25:06,116 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 27, in results
    articles= models.Article.query.filter(models.Article.default_set == False).order_by(models.Article.score.desc()).all()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2300, in all
    return list(self)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
    return self._execute_and_instances(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2427, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) no such table: article u'SELECT article.id AS article_id, article.title AS article_title, article.doi AS article_doi, article.journal AS article_journal, article.score AS article_score, article.abstract AS article_abstract, article.default_set AS article_default_set, article.pub_date AS article_pub_date \nFROM article \nWHERE article.default_set = 0 ORDER BY article.score DESC' ()
2015-09-14 20:25:08,077 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 27, in results
    articles= models.Article.query.filter(models.Article.default_set == False).order_by(models.Article.score.desc()).all()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2300, in all
    return list(self)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
    return self._execute_and_instances(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2427, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) no such table: article u'SELECT article.id AS article_id, article.title AS article_title, article.doi AS article_doi, article.journal AS article_journal, article.score AS article_score, article.abstract AS article_abstract, article.default_set AS article_default_set, article.pub_date AS article_pub_date \nFROM article \nWHERE article.default_set = 0 ORDER BY article.score DESC' ()
2015-09-14 20:25:09,876 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 27, in results
    articles= models.Article.query.filter(models.Article.default_set == False).order_by(models.Article.score.desc()).all()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2300, in all
    return list(self)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
    return self._execute_and_instances(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2427, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) no such table: article u'SELECT article.id AS article_id, article.title AS article_title, article.doi AS article_doi, article.journal AS article_journal, article.score AS article_score, article.abstract AS article_abstract, article.default_set AS article_default_set, article.pub_date AS article_pub_date \nFROM article \nWHERE article.default_set = 0 ORDER BY article.score DESC' ()
2015-09-14 20:25:17,252 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 27, in results
    articles= models.Article.query.filter(models.Article.default_set == False).order_by(models.Article.score.desc()).all()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2300, in all
    return list(self)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
    return self._execute_and_instances(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2427, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) no such table: article u'SELECT article.id AS article_id, article.title AS article_title, article.doi AS article_doi, article.journal AS article_journal, article.score AS article_score, article.abstract AS article_abstract, article.default_set AS article_default_set, article.pub_date AS article_pub_date \nFROM article \nWHERE article.default_set = 0 ORDER BY article.score DESC' ()
2015-09-14 20:25:26,867 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 20:25:32,641 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 20:25:38,822 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 20:25:44,769 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 20:25:48,181 ERROR: Exception on /search [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 46, in search
    old_articles= models.Article.query.all()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2300, in all
    return list(self)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
    return self._execute_and_instances(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2427, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) no such table: article u'SELECT article.id AS article_id, article.title AS article_title, article.doi AS article_doi, article.journal AS article_journal, article.score AS article_score, article.abstract AS article_abstract, article.default_set AS article_default_set, article.pub_date AS article_pub_date \nFROM article' ()
2015-09-14 20:30:27,406 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 20:41:15,455 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 20:41:50,427 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-14 20:44:30,458 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 20:46:35,434 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-14 20:54:26,854 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 20:54:51,388 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 20:55:16,391 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 20:55:27,861 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 20:55:33,221 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 20:55:35,909 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 20:55:52,364 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 20:56:27,337 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:00:08,332 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:01:00,319 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:02:03,575 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:02:44,582 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:03:05,566 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:03:17,372 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:03:53,397 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:04:00,011 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:06:49,862 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:07:14,850 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:07:44,265 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:08:42,113 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-14 21:09:09,585 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:12:40,562 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:12:52,470 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:12:58,477 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:13:04,397 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:14:35,241 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-14 21:15:51,587 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:16:03,556 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-14 21:16:32,666 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:16:53,451 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:19:13,519 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:19:19,336 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:19:25,246 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:21:51,856 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-14 21:23:11,010 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:24:52,802 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:24:58,675 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:25:04,620 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:25:07,638 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:25:10,721 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:25:11,551 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 31, in results
    return render_template('results.html', title='', form=form, articles=articles)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/app/templates/results.html", line 53, in top-level template code
    {% for article in articles %}
TypeError: 'Article' object is not iterable
2015-09-14 21:25:34,726 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 31, in results
    return render_template('results.html', title='', form=form, articles=articles)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/app/templates/results.html", line 53, in top-level template code
    {% for article in articles %}
TypeError: 'Article' object is not iterable
2015-09-14 21:25:35,618 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 31, in results
    return render_template('results.html', title='', form=form, articles=articles)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/app/templates/results.html", line 53, in top-level template code
    {% for article in articles %}
TypeError: 'Article' object is not iterable
2015-09-14 21:25:40,030 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 31, in results
    return render_template('results.html', title='', form=form, articles=articles)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/app/templates/results.html", line 53, in top-level template code
    {% for article in articles %}
TypeError: 'Article' object is not iterable
2015-09-14 21:25:46,695 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:25:52,115 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:25:54,464 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 31, in results
    return render_template('results.html', title='', form=form, articles=articles)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/app/templates/results.html", line 53, in top-level template code
    {% for article in articles %}
TypeError: 'Article' object is not iterable
2015-09-14 21:26:22,047 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-14 21:27:01,023 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 31, in results
    return render_template('results.html', title='', form=form, articles=articles)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/app/templates/results.html", line 53, in top-level template code
    {% for article in articles %}
TypeError: 'Article' object is not iterable
2015-09-14 21:27:01,673 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 31, in results
    return render_template('results.html', title='', form=form, articles=articles)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/app/templates/results.html", line 53, in top-level template code
    {% for article in articles %}
TypeError: 'Article' object is not iterable
2015-09-14 21:27:02,199 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 31, in results
    return render_template('results.html', title='', form=form, articles=articles)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/app/templates/results.html", line 53, in top-level template code
    {% for article in articles %}
TypeError: 'Article' object is not iterable
2015-09-14 21:27:02,628 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 31, in results
    return render_template('results.html', title='', form=form, articles=articles)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/app/templates/results.html", line 53, in top-level template code
    {% for article in articles %}
TypeError: 'Article' object is not iterable
2015-09-14 21:27:07,697 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:27:28,174 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:27:35,783 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:27:41,711 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:28:37,825 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:29:03,574 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:29:09,651 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:29:43,323 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:29:44,676 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 31, in results
    return render_template('results.html', title='', form=form, articles=articles)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/app/templates/results.html", line 53, in top-level template code
    {% for article in articles %}
TypeError: 'Article' object is not iterable
2015-09-14 21:29:48,193 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 31, in results
    return render_template('results.html', title='', form=form, articles=articles)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/app/templates/results.html", line 53, in top-level template code
    {% for article in articles %}
TypeError: 'Article' object is not iterable
2015-09-14 21:29:48,878 ERROR: Exception on /results [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 31, in results
    return render_template('results.html', title='', form=form, articles=articles)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/app/templates/results.html", line 53, in top-level template code
    {% for article in articles %}
TypeError: 'Article' object is not iterable
2015-09-14 21:29:58,642 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:30:04,530 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-14 21:30:15,516 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-15 09:04:27,799 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-15 09:04:28,912 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-15 09:04:57,352 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-15 09:05:08,443 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-15 09:05:11,404 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-15 09:05:19,485 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-15 09:05:22,750 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-15 19:20:26,358 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-15 19:20:27,685 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-15 19:26:13,556 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-15 19:32:59,046 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-15 20:10:24,535 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-15 20:10:37,575 ERROR: Exception on /search [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 53, in search
    articles= query_local_database(query)
NameError: global name 'query' is not defined
2015-09-15 20:11:55,045 ERROR: Exception on /search [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 53, in search
    articles= query_local_database(query)
NameError: global name 'query' is not defined
2015-09-15 20:11:55,844 ERROR: Exception on /search [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 53, in search
    articles= query_local_database(query)
NameError: global name 'query' is not defined
2015-09-15 20:11:56,363 ERROR: Exception on /search [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 53, in search
    articles= query_local_database(query)
NameError: global name 'query' is not defined
2015-09-15 20:11:56,908 ERROR: Exception on /search [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 53, in search
    articles= query_local_database(query)
NameError: global name 'query' is not defined
2015-09-15 20:11:57,368 ERROR: Exception on /search [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 53, in search
    articles= query_local_database(query)
NameError: global name 'query' is not defined
2015-09-15 20:11:57,830 ERROR: Exception on /search [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 53, in search
    articles= query_local_database(query)
NameError: global name 'query' is not defined
2015-09-15 20:11:58,358 ERROR: Exception on /search [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 53, in search
    articles= query_local_database(query)
NameError: global name 'query' is not defined
2015-09-15 20:12:05,217 ERROR: Exception on /search [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 53, in search
    articles= query_local_database(query)
NameError: global name 'query' is not defined
2015-09-15 20:12:17,870 ERROR: Exception on /search [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 53, in search
    articles= query_local_database(query)
NameError: global name 'query' is not defined
2015-09-15 20:12:21,946 ERROR: Exception on /search [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 53, in search
    articles= query_local_database(query)
NameError: global name 'query' is not defined
2015-09-15 20:15:53,091 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-15 20:15:55,021 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 53, in search
    articles= query_local_database(query)
NameError: global name 'query' is not defined
2015-09-15 20:16:00,433 ERROR: Exception on /search [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 53, in search
    articles= query_local_database(query)
NameError: global name 'query' is not defined
2015-09-15 20:16:13,044 ERROR: Exception on /search [GET] [in /services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/services/http/users/a/aherns/sciral/flask/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/services/http/users/a/aherns/sciral/app/views.py", line 53, in search
    articles= query_local_database(query)
NameError: global name 'query' is not defined
2015-09-15 20:17:48,054 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-15 20:17:53,218 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-15 20:17:57,793 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-15 20:18:02,677 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
2015-09-15 20:23:01,035 INFO: sciral-dev startup [in app/__init__.py:17]
2015-09-15 20:28:04,065 INFO: sciral-dev startup [in /services/http/users/a/aherns/sciral/app/__init__.py:17]
